version: '3.9'

services:

  conduktor:
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      conduktor-proxy:
        condition: service_started

  # https://docs.conduktor.io/platform/proxy/configuration/env-variables#proxy-environment-variables
  conduktor-proxy:
    image: conduktor/conduktor-proxy:0.3.0-amd64
    hostname: conduktor-proxy
    container_name: conduktor-proxy
    ports:
      - "8888:8888"
      - "6969:6969"
      - "6970:6970"
    environment:
      TZ: $TZ
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PROXY_HOST: conduktor-proxy
      SCHEMA_REGISTRY_HOST: http://schema-registry:8081