organization:
  name: default

clusters:
  - id: local
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}"
    properties: |
      client.id=conduktor
      default.api.timeout.ms=5000
      request.timeout.ms=5000
    schemaRegistry:
      url: "${SCHEMA_REGISTRY_URL:-http://localhost:8081}"
      ignoreUntrustedCertificate: false
      properties: |
        acks=all
        client.id=conduktor
        default.api.timeout.ms=5000
        request.timeout.ms=5000
    labels:
      env: default

envs : []

auth:
  local-users:
    - email: admin@conduktor.io
      password: admin
    - email: user@conduktor.io
      password: user

license: ${LICENSE_KEY:-~} # Fallback to null (~)
