organization:
  name: "${ORGANISATION_NAME}"

clusters:
  - id: default
    name: Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties: |
      client.id=conduktor
      default.api.timeout.ms=5000
      request.timeout.ms=5000
    schemaRegistry:
      url: "$SCHEMA_REGISTRY_URL"
      ignoreUntrustedCertificate: false
      properties: |
        acks=all
        client.id=conduktor
        default.api.timeout.ms=5000
        request.timeout.ms=5000
    labels: {}
    kafkaConnects:
      - url: http://kafka-connect-01:8083
        name: Kafka connect worker 1
      - url: http://kafka-connect-02:8083
        name: Kafka connect worker 2
      - url: http://kafka-connect-03:8083
        name: Kafka connect worker 3
  - id: proxy
    name: Proxy
    color: "#0013E8"
    ignoreUntrustedCertificate: false
    bootstrapServers: "conduktor-proxy:6969"
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    labels: { }

auth:
  demo-users:
    - email: "${ADMIN_EMAIL}"
      password: "${ADMIN_PSW}"
      groups:
        - ADMIN

license: ${LICENSE_KEY:-~} # Fallback to null (~)